# Generated by Django 3.0.5 on 2020-04-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cosmetic_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='flat_number',
            field=models.CharField(blank=True, editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='province',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='street_number',
            field=models.CharField(blank=True, editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='zip_code',
            field=models.CharField(blank=True, editable=False, help_text='Valid zip code (000000)', max_length=6),
        ),
    ]
