# Generated by Django 3.0.5 on 2020-04-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200430_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmetic',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=9),
        ),
    ]
