# Generated by Django 3.0.5 on 2020-04-30 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20200501_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritecosmetic',
            name='profile',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_cosmetics', to=settings.AUTH_USER_MODEL),
        ),
    ]
