# Generated by Django 3.0.5 on 2020-04-30 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200501_0531'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favoritecosmetic',
            name='unique_favorite_cosmetics',
        ),
    ]
