# Generated by Django 3.0.5 on 2020-05-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200501_0532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritecosmetic',
            name='cosmetic',
        ),
        migrations.AddField(
            model_name='favoritecosmetic',
            name='cosmetics',
            field=models.ManyToManyField(to='core.Cosmetic'),
        ),
    ]
