# Generated by Django 3.0.5 on 2020-05-04 11:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_userfav'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfav',
            options={'verbose_name': 'Favorites', 'verbose_name_plural': 'Favorites'},
        ),
        migrations.AlterField(
            model_name='userfav',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='added date'),
        ),
        migrations.AlterField(
            model_name='userfav',
            name='cosmetics',
            field=models.ForeignKey(help_text='selected', on_delete=django.db.models.deletion.CASCADE, to='core.Cosmetic', verbose_name='favorites'),
        ),
        migrations.AlterField(
            model_name='userfav',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
