# Generated by Django 3.0.5 on 2020-05-04 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200504_1747'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteCosmetic',
        ),
    ]
