# Generated by Django 3.0.5 on 2020-05-05 11:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_bankcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcard',
            name='CVC',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='date',
            field=models.CharField(max_length=5, verbose_name='expiration date'),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='number',
            field=models.DecimalField(decimal_places=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='order',
            name='street',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='bankcard',
            unique_together={('user', 'number')},
        ),
    ]
