# Generated by Django 3.0.5 on 2020-05-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200505_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmetic',
            name='image_url',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
    ]
