# Generated by Django 3.0.5 on 2020-05-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_cosmetic_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmetic',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
