# Generated by Django 3.0.5 on 2020-05-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200511_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmetic',
            name='target_area',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
